### ISSUE TITLE
Cannot insert data - unauthorized

### ISSUE THREAD

**Issue by suityou01** [node-influx/node-influx#586]
## Expected Behavior
Can write a measurement

## Actual Behavior
Fails with unauthorized

## Steps/Code to Reproduce the Problem

Run docker-compose with the following config
```
version: "3"
services: 
    web:
        build: .
        ports: 
            - "3333:3333"
        volumes:
            - .:/app
    influxdb:
        image: influxdb
        ports:
            - "8086:8086"
        environment: 
            - DOCKER_INFLUXDB_INIT_USERNAME=charlie \
            - DOCKER_INFLUXDB_INIT_PASSWORD=password \
            - DOCKER_INFLUXDB_INIT_ORG=charlie \
            - DOCKER_INFLUXDB_INIT_BUCKET=charliebucket \
        volumes: 
            - ./data:/var/lib/influxdb2
            - ./config:/etc/influxdb2
```

In the container run the influx setup. Supply a username and password during setup.

From the web client run the following code

```
import dotenv from 'dotenv';
dotenv.config();

import Influx from 'influx';

const db = new Influx.InfluxDB({
    host: process.env.INFLUXHOSTNAME,
    database: process.env.INFLUXDBNAME,
    username: "charlie",
    password: "password",
    schema: [
      {
        measurement: 'vivarium_environment_sensors',
        fields: {
            hotend_h: Influx.FieldType.FLOAT,
            hotend_t: Influx.FieldType.FLOAT,
            hotend_f: Influx.FieldType.FLOAT,
            hotend_hic: Influx.FieldType.FLOAT,
            hotend_hif: Influx.FieldType.FLOAT,
            coldend_h: Influx.FieldType.FLOAT,
            coldend_t: Influx.FieldType.FLOAT,
            coldend_f: Influx.FieldType.FLOAT,
            coldend_hic: Influx.FieldType.FLOAT,
            coldend_hif: Influx.FieldType.FLOAT,
            ambient_h: Influx.FieldType.FLOAT,
            ambient_t: Influx.FieldType.FLOAT,
            ambient_f: Influx.FieldType.FLOAT,
            ambient_hic: Influx.FieldType.FLOAT,
            ambient_hif: Influx.FieldType.FLOAT,
            uva: Influx.FieldType.FLOAT,
            uvb: Influx.FieldType.FLOAT,
            uvi: Influx.FieldType.FLOAT
        },
        tags: []
    }
    ]
});
```

Run the write command as per the following method

```
static submitReading = async ( reading ) => {
        await db.writePoints([
            {
                measurement: 'vivarium_environment_sensors',
                fields: 
                {   hotend_h: reading.hotend.h,
                    hotend_t: reading.hotend.t,
                    hotend_f: reading.hotend.f,
                    hotend_hic: reading.hotend.hic,  
                    hotend_hif: reading.hotend.hif,  
                    coldend_h: reading.coldend.h,
                    coldend_t: reading.coldend.t,
                    coldend_f: reading.coldend.f,
                    coldend_hic: reading.coldend.hic,  
                    coldend_hif: reading.coldend.hif,  
                    ambient_h: reading.ambient.h,
                    ambient_t: reading.ambient.t,
                    ambient_f: reading.ambient.f,
                    ambient_hic: reading.ambient.hic,  
                    ambient_hif: reading.ambient.hif,  
                    uva: reading.uv.uva,
                    uvb: reading.uv.uvb,
                    uvi: reading.uv.uvi  
                }
            }
        ]);
    }
```

Get the following error

```
RequestError: A 401 Unauthorized error occurred: {"code":"unauthorized","message":"Unauthorized"}
web_1       |     at IncomingMessage.<anonymous> (/app/node_modules/influx/lib/src/pool.js:50:38)
```

## Specifications

- Version: 2
- Platform: Docker
- Subsystem: Linux
